application: team-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: login.app

- url: /login
  script: login.app

- url: /student
  script: student.app

- url: /teacher
  script: teacher.app

- url: /signup
  script: signup.app