application: team-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: login.app

- url: /login
  script: login.app

- url: /student
  script: student.app

- url: /teacher
  script: teacher.app

- url: /teacher/review
  script: review.app

- url: /releaseassignment
  script: teacher.app

- url: /editassignment
  script: teacher.app

- url: /signup
  script: signup.app

- url: /createteam
  script: createTeam.app

- url: /tagcollection
  script: tagCollection.app

- url: /assignmentwall
  script: tagCollection.app

- url: /upload
  script: upload.app

- url: /team
  script: team.app


